### ISSUE TITLE
Upgrade to Tailwind 1.4.x and check built-in purging

### ISSUE THREAD

**Issue by yonigibbs** [monty5811/postcss-elm-tailwind#23]
Tailwind 1.4.x is now out, and has [built in purging](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.4.0#built-in-purgecss). The examples in this repo currently use `fullhuman/postcss-purgecss` to do this. It would be good to know if this is still required, or if the built-in purging from Tailwind can now be used directly without the need for this plugin. If so, the samples/demo should be updated accordingly.

**Comment by sparksp** [comment]
1. You can use tailwind purge without any modifications, you just need to point it at your content files:
```js
// tailwind.config.js
module.exports = {
  purge: {
    content: ["./index.html", "./dist/main.css"]
  },
  // other tailwind options
}
```

2. Tailwind's purge whitelists everything except the tailwind utilities by default. If you have added your own styles that you want to purge then you can [end the whitelist in the css](https://purgecss.com/whitelisting.html#in-the-css-directly). In the demo, without these comments all of the font awesome styles are untouched.
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

.never-purged {
    visibility: inherit;
}

/* purgecss end ignore */
.maybe-purged {
    opacity: inherit;
}
/* purgecss start ignore */
```

3. Or you can use the `mode` option to [remove all unused styles](https://tailwindcss.com/docs/controlling-file-size/#removing-all-unused-styles).
```js
// tailwind.config.js
module.exports = {
  purge: {
    mode: 'all', // purge your own css too
    content: ['./index.html', './dist/app.js']
  },
  // other options here
};
```

4. I found that tailwind's default extractor works well, but you can override this if you want.  [Consider using an extractor](https://purgecss.com/extractors.html#using-an-extractor) rather than replacing the `defaultExtractor`.
```js
// tailwind.config.js
module.exports = {
  purge: {
    content: ["./index.html", "./dist/main.css"],
    options: {
      extractors: [ /* extractors here */ ]
    }
}
```

5. Do not use `purge.enabled = true` as postcss-elm-tailwind needs the complete tailwind css!
```js
// tailwind.config.js
module.exports = {
  purge: {
    // postcss-elm-tailwind will not work with `purge.enabled = true`
    enabled: true,
    content: ["./index.html", "./dist/main.css"]
  },
  // other options here
}
```

6. You can use your own purgecss config, just turn off tailwind purge first:
```js
// tailwind.config.js
module.exports = {
  purge: false,
  // other tailwind options here
}
```

7. If you don't disable tailwind purge then your purgecss will still work but you'll get a warning from tailwind in the console:
> Tailwind is not purging unused styles because no template paths have been provided. If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
>
>   https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
